version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: day2-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: day2-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/day2db
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: day2-client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data: