server {
    listen 80;
    server_name local.day4.test;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name local.day4.test;

    ssl_certificate /etc/ssl/certs/local.day4.test.pem;
    ssl_certificate_key /etc/ssl/certs/local.day4.test-key.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}